# Generated by Django 5.2.7 on 2025-11-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coin_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='coingecko_id',
            field=models.CharField(blank=True, help_text="e.g. 'bitcoin', 'ethereum'", max_length=100, null=True),
        ),
    ]
